name: build

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build.yml'
      - '*'  # Trigger the workflow for changes in any file in the root directory
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/build.yml'
      - '*'  # Trigger the workflow for changes in any file in the root directory
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set variables
        id: setup
        run: |
          COMMIT_NUM=$(git rev-list --count HEAD)
          COMMIT_HASH=$(git rev-parse --short HEAD)
          VERSION=$(jq -r .version update.json)
          ZIP_NAME="SMTW_${VERSION}-${COMMIT_NUM}-${COMMIT_HASH}"
          echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV

      - name: Create ZIP
        run: |
          zip -r "${{ env.ZIP_NAME }}.zip" ./* \
            -x ".git*" \
            -x ".github*" \
            -x "README.md" \
            -x "SMTW-Banner.jpg" \
            -x "update.json" \
            -x "UPDATE.md" \
            -x "SuperMarioTweaker-test-*.zip"

      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ZIP_NAME }}  # Name the artifact as the ZIP file name
          path: ${{ env.ZIP_NAME }}.zip  # Upload the ZIP file, not the directory
