name: build test package

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/build.yml'  # Workflow file
      - 'update.json'                  # Update JSON (if necessary)
      - '*'                             # Any other change in the root directory
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/build.yml'  # Workflow file
      - 'update.json'                  # Update JSON (if necessary)
      - '*'                             # Any other change in the root directory
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Full history, required for accurate commit count

      - name: Set variables
        id: setup
        run: |
          COMMIT_NUM=$(git rev-list --count HEAD)
          COMMIT_HASH=$(git rev-parse --short HEAD)
          VERSION=$(jq -r .version update.json)
          ZIP_NAME="SMTW_${VERSION}-${COMMIT_NUM}-${COMMIT_HASH}"
          echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV

      - name: Create ZIP file
        run: |
          zip -r "${ZIP_NAME}.zip" ./* \
            -x ".git/*" \
            -x ".github/*" \
            -x "README.md" \
            -x "SMTW-Banner.jpg" \
            -x "update.json" \
            -x "UPDATE.md" \
            -x "*.zip"
      
      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ZIP_NAME }}             # No .zip here
          path: ${{ env.ZIP_NAME }}.zip         # .zip added only here
